spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hu
    username: root
    password: 2006722Hjb%
  session:
    timeout: 86400
server:
  port: 8080
  servlet:
    context-path: /api
#数据库 字段驼峰和下划线关系的问题 把它改成false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
